### PR TITLE
Add Quick Search

### PR DESCRIPTION
**Pull request by ekuusela**
Added a link to Quick Search, the best search tool I've come across.

### CODE REVIEW

**Comment by hrj** [comment]
This sounds great, thanks!

I am not able to install it however. I tried with the following update site URLs:

```
http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/
http://dist.springsource.com/snapshot/TOOLS/eclipse-integration-commons/nightly/e4.4 
http://dist.springsource.com/milestone/TOOLS/eclipse-integration-commons/e4.4
http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/e4.4
```

But none of them work. Which URL do you use?

**Comment by hrj** [comment]
Raised an issue upstream: https://github.com/spring-projects/eclipse-integration-commons/issues/12

**Comment by ekuusela** [comment]
I always install from the Eclipse Marketplace (search for “Quick Search”).

**Comment by hrj** [comment]
The first update site is now working `http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/`

The search with this plugin is really very fast. Thanks for the PR.

**Pull request merged**
